In [25]:
import pandas as pd

In [27]:
scraped_salary = pd.read_csv('nfl_salary_cash_2020_2024.csv')

In [29]:
scraped_salary

,Year,Rank,Team,Record,Signed Players,Avg Age,Active Cash,Dead Cash,Total Cash
0,2020,1,HOU,4-12-0,55,26.3,"$192,489,580","$16,986,836","$261,735,595"
1,2020,2,NO,12-4-0,53,27.0,"$233,445,421","$9,000,166","$253,584,935"
2,2020,3,DAL,6-10-0,52,25.9,"$159,376,968","$21,631,582","$249,805,299"
3,2020,4,LAC,7-9-0,55,25.5,"$201,860,615","$6,506,526","$247,147,613"
4,2020,5,SF,6-10-0,55,26.4,"$139,826,064","$20,917,873","$243,983,860"
...,...,...,...,...,...,...,...,...,...
155,2024,28,LAC,11-6-0,53,26.6,"$217,240,689","$6,675,070","$238,941,583"
156,2024,29,SEA,10-7-0,52,26.1,"$180,217,001","$22,243,030","$229,031,876"
157,2024,30,PIT,10-7-0,51,27.6,"$181,565,548","$6,560,159","$225,450,918"
158,2024,31,LAR,10-7-0,53,25.9,"$201,928,187","$7,621,992","$219,121,282"
159,2024,32,LV,4-13-0,53,25.6,"$116,277,872","$16,060,450","$213,387,197"

In [31]:
team_data = pd.read_csv('nfl_team_data.csv')
team_data

,Date,DOW,WT,LT,WTS,LTS,Type,Season
0,9/10/20,Thu,Kansas City Chiefs,Houston Texans,34,20,Regular Season,2020
1,9/13/20,Sun,Seattle Seahawks,Atlanta Falcons,38,25,Regular Season,2020
2,9/13/20,Sun,Buffalo Bills,New York Jets,27,17,Regular Season,2020
3,9/13/20,Sun,Las Vegas Raiders,Carolina Panthers,34,30,Regular Season,2020
4,9/13/20,Sun,Chicago Bears,Detroit Lions,27,23,Regular Season,2020
...,...,...,...,...,...,...,...,...
1403,1/19/25,Sun,Philadelphia Eagles,Los Angeles Rams,28,22,Playoff,2024
1404,1/19/25,Sun,Buffalo Bills,Baltimore Ravens,27,25,Playoff,2024
1405,1/26/25,Sun,Philadelphia Eagles,Washington Commanders,55,23,Playoff,2024
1406,1/26/25,Sun,Kansas City Chiefs,Buffalo Bills,32,29,Playoff,2024
1407,2/9/25,Sun,Philadelphia Eagles,Kansas City Chiefs,40,22,Playoff,2024

In [33]:
team_mapping = {
    "HOU": "Houston Texans",
    "NO": "New Orleans Saints",
    "DAL": "Dallas Cowboys",
    "LAC": "Los Angeles Chargers",
    "SF": "San Francisco 49ers",
    "PHI": "Philadelphia Eagles",
    "LV": "Las Vegas Raiders",
    "CIN": "Cincinnati Bengals",
    "MIA": "Miami Dolphins",
    "PIT": "Pittsburgh Steelers",
    "BAL": "Baltimore Ravens",
    "GB": "Green Bay Packers",
    "BUF": "Buffalo Bills",
    "TEN": "Tennessee Titans",
    "NYJ": "New York Jets",
    "SEA": "Seattle Seahawks",
    "KC": "Kansas City Chiefs",
    "LA": "Los Angeles Rams",
    "NE": "New England Patriots",
    "CHI": "Chicago Bears",
    "MIN": "Minnesota Vikings",
    "IND": "Indianapolis Colts",
    "ATL": "Atlanta Falcons",
    "CAR": "Carolina Panthers",
    "DET": "Detroit Lions",
    "JAX": "Jacksonville Jaguars",
    "NYG": "New York Giants",
    "WAS": "Washington Commanders",
    "ARI": "Arizona Cardinals",
    "CLE": "Cleveland Browns",
    "TB": "Tampa Bay Buccaneers",
    "LAR": "Los Angeles Rams",
    "DEN": "Denver Broncos"
}

In [35]:
scraped_salary['Team Name'] = scraped_salary['Team'].replace(team_mapping)
scraped_salary

,Year,Rank,Team,Record,Signed Players,Avg Age,Active Cash,Dead Cash,Total Cash,Team Name
0,2020,1,HOU,4-12-0,55,26.3,"$192,489,580","$16,986,836","$261,735,595",Houston Texans
1,2020,2,NO,12-4-0,53,27.0,"$233,445,421","$9,000,166","$253,584,935",New Orleans Saints
2,2020,3,DAL,6-10-0,52,25.9,"$159,376,968","$21,631,582","$249,805,299",Dallas Cowboys
3,2020,4,LAC,7-9-0,55,25.5,"$201,860,615","$6,506,526","$247,147,613",Los Angeles Chargers
4,2020,5,SF,6-10-0,55,26.4,"$139,826,064","$20,917,873","$243,983,860",San Francisco 49ers
...,...,...,...,...,...,...,...,...,...,...
155,2024,28,LAC,11-6-0,53,26.6,"$217,240,689","$6,675,070","$238,941,583",Los Angeles Chargers
156,2024,29,SEA,10-7-0,52,26.1,"$180,217,001","$22,243,030","$229,031,876",Seattle Seahawks
157,2024,30,PIT,10-7-0,51,27.6,"$181,565,548","$6,560,159","$225,450,918",Pittsburgh Steelers
158,2024,31,LAR,10-7-0,53,25.9,"$201,928,187","$7,621,992","$219,121,282",Los Angeles Rams
159,2024,32,LV,4-13-0,53,25.6,"$116,277,872","$16,060,450","$213,387,197",Las Vegas Raiders

In [37]:
name_correction = {
    "Washington Football Team": "Washington Commanders",
    "Washington Commanders": "Washington Commanders"
}

In [39]:
team_data.rename(columns={'WT':'Winning Team Name','LT':'Losing Team','Season':'Year','WTS':'Winning Team Score','LTS':'Losing Team Score','DOW':'Day of Week'},inplace=True)
team_data

,Date,Day of Week,Winning Team Name,Losing Team,Winning Team Score,Losing Team Score,Type,Year
0,9/10/20,Thu,Kansas City Chiefs,Houston Texans,34,20,Regular Season,2020
1,9/13/20,Sun,Seattle Seahawks,Atlanta Falcons,38,25,Regular Season,2020
2,9/13/20,Sun,Buffalo Bills,New York Jets,27,17,Regular Season,2020
3,9/13/20,Sun,Las Vegas Raiders,Carolina Panthers,34,30,Regular Season,2020
4,9/13/20,Sun,Chicago Bears,Detroit Lions,27,23,Regular Season,2020
...,...,...,...,...,...,...,...,...
1403,1/19/25,Sun,Philadelphia Eagles,Los Angeles Rams,28,22,Playoff,2024
1404,1/19/25,Sun,Buffalo Bills,Baltimore Ravens,27,25,Playoff,2024
1405,1/26/25,Sun,Philadelphia Eagles,Washington Commanders,55,23,Playoff,2024
1406,1/26/25,Sun,Kansas City Chiefs,Buffalo Bills,32,29,Playoff,2024
1407,2/9/25,Sun,Philadelphia Eagles,Kansas City Chiefs,40,22,Playoff,2024

In [41]:
team_data['Winning Team Name'] = team_data['Winning Team Name'].replace(name_correction)
team_data['Losing Team']=team_data['Losing Team'].replace(name_correction)
team_data

,Date,Day of Week,Winning Team Name,Losing Team,Winning Team Score,Losing Team Score,Type,Year
0,9/10/20,Thu,Kansas City Chiefs,Houston Texans,34,20,Regular Season,2020
1,9/13/20,Sun,Seattle Seahawks,Atlanta Falcons,38,25,Regular Season,2020
2,9/13/20,Sun,Buffalo Bills,New York Jets,27,17,Regular Season,2020
3,9/13/20,Sun,Las Vegas Raiders,Carolina Panthers,34,30,Regular Season,2020
4,9/13/20,Sun,Chicago Bears,Detroit Lions,27,23,Regular Season,2020
...,...,...,...,...,...,...,...,...
1403,1/19/25,Sun,Philadelphia Eagles,Los Angeles Rams,28,22,Playoff,2024
1404,1/19/25,Sun,Buffalo Bills,Baltimore Ravens,27,25,Playoff,2024
1405,1/26/25,Sun,Philadelphia Eagles,Washington Commanders,55,23,Playoff,2024
1406,1/26/25,Sun,Kansas City Chiefs,Buffalo Bills,32,29,Playoff,2024
1407,2/9/25,Sun,Philadelphia Eagles,Kansas City Chiefs,40,22,Playoff,2024

In [50]:
# Merge salary info for winning teams
combined = pd.merge(
    team_data,
    scraped_salary,
    how='left',
    left_on=['Winning Team Name', 'Year'],
    right_on=['Team Name', 'Year']
)

# Rename winning team columns
combined = combined.rename(columns={
    'Rank': 'Winning Rank',
    'Team': 'Winning Team Code',
    'Record': 'Winning Record',
    'Signed Players': 'Winning Signed Players',
    'Avg Age': 'Winning Avg Age',
    'Active Cash': 'Winning Active Cash',
    'Dead Cash': 'Winning Dead Cash',
    'Total Cash': 'Winning Total Cash'
})

# Drop extra 'Team Name' from winning team join
combined = combined.drop(columns=['Team Name'])

# Merge salary info for losing teams
combined = pd.merge(
    combined,
    scraped_salary,
    how='left',
    left_on=['Losing Team', 'Year'],
    right_on=['Team Name', 'Year']
)

# Rename losing team columns
combined = combined.rename(columns={
    'Rank': 'Losing Rank',
    'Team': 'Losing Team Code',
    'Record': 'Losing Record',
    'Signed Players': 'Losing Signed Players',
    'Avg Age': 'Losing Avg Age',
    'Active Cash': 'Losing Active Cash',
    'Dead Cash': 'Losing Dead Cash',
    'Total Cash': 'Losing Total Cash'
})

# Drop extra 'Team Name' from losing team join
combined = combined.drop(columns=['Team Name'])
combined

,Date,Day of Week,Winning Team Name,Losing Team,Winning Team Score,Losing Team Score,Type,Year,Winning Rank,Winning Team Code,...,Winning Dead Cash,Winning Total Cash,Losing Rank,Losing Team Code,Losing Record,Losing Signed Players,Losing Avg Age,Losing Active Cash,Losing Dead Cash,Losing Total Cash
0,9/10/20,Thu,Kansas City Chiefs,Houston Texans,34,20,Regular Season,2020,25,KC,...,"$7,823,872","$202,794,195",1,HOU,4-12-0,55,26.3,"$192,489,580","$16,986,836","$261,735,595"
1,9/13/20,Sun,Seattle Seahawks,Atlanta Falcons,38,25,Regular Season,2020,18,SEA,...,"$10,804,732","$221,174,179",24,ATL,4-12-0,54,26.7,"$193,036,066","$9,433,853","$205,770,850"
2,9/13/20,Sun,Buffalo Bills,New York Jets,27,17,Regular Season,2020,15,BUF,...,"$10,187,390","$223,199,805",30,NYJ,2-14-0,53,25.3,"$95,099,002","$38,764,517","$179,996,030"
3,9/13/20,Sun,Las Vegas Raiders,Carolina Panthers,34,30,Regular Season,2020,7,LV,...,"$8,765,225","$234,936,034",22,CAR,5-11-0,53,26.0,"$174,053,397","$11,825,322","$212,688,413"
4,9/13/20,Sun,Chicago Bears,Detroit Lions,27,23,Regular Season,2020,12,CHI,...,"$8,116,625","$228,516,276",27,DET,5-11-0,52,26.8,"$141,794,789","$9,075,111","$200,759,182"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,1/19/25,Sun,Philadelphia Eagles,Los Angeles Rams,28,22,Playoff,2024,3,PHI,...,"$15,079,844","$328,556,211",31,LAR,10-7-0,53,25.9,"$201,928,187","$7,621,992","$219,121,282"
1404,1/19/25,Sun,Buffalo Bills,Baltimore Ravens,27,25,Playoff,2024,14,BUF,...,"$16,268,495","$285,254,387",25,BAL,12-5-0,54,26.6,"$240,249,948","$8,637,184","$258,750,391"
1405,1/26/25,Sun,Philadelphia Eagles,Washington Commanders,55,23,Playoff,2024,3,PHI,...,"$15,079,844","$328,556,211",20,WAS,12-5-0,53,27.5,"$251,683,516","$14,561,554","$273,578,070"
1406,1/26/25,Sun,Kansas City Chiefs,Buffalo Bills,32,29,Playoff,2024,11,KC,...,"$15,314,769","$293,739,868",14,BUF,13-4-0,53,26.9,"$262,492,400","$16,268,495","$285,254,387"
1407,2/9/25,Sun,Philadelphia Eagles,Kansas City Chiefs,40,22,Playoff,2024,3,PHI,...,"$15,079,844","$328,556,211",11,KC,15-2-0,53,26.5,"$266,722,742","$15,314,769","$293,739,868"

In [52]:
combined.to_csv("combined_nfl_data.csv")